version: '3.8'

services:
    app:
        container_name: api
        user: 'node'
        restart: unless-stopped
        env_file: .env
        command: 'npm run dev'
        ports:
            - ${PORT}:${PORT}
        environment:
            - TOKEN=${TOKEN}
            - PORT=${PORT}
            - MONGODB_ENABLED=${MONGODB_ENABLED}
            - MONGODB_URL=${MONGODB_URL}
            - WEBHOOK_ENABLED=${WEBHOOK_ENABLED}
            - WEBHOOK_URL=${WEBHOOK_URL}
            - WEBHOOK_BASE64=${WEBHOOK_BASE64}
        volumes:
            - ./:/home/node/app
        working_dir: /home/node/app
        image: node:17.2.0-alpine

volumes:
    db:
